---
title: "train_model"
author: "Sander Devisscher"
date: "2024-11-20"
output: html_document
---

```{r set frequency range}
min.freq <- 200
max.freq <- 3900
```

```{r install gibonR, eval = FALSE}
devtools::install_github("DenaJGibbon/gibbonR")
```

```{r libraries, message=FALSE, warning=FALSE}
library(gibbonR)
library(tidyverse)
library(randomForest)
```

```{r get testdata classificationfile}
classification <- read_delim("input/testdata/classification.txt", 
                             delim = ";", escape_double = FALSE, col_types = cols(filename = col_character(), 
                                                                                  classification = col_character()), 
                             trim_ws = TRUE)
```

```{r create trainingdata from folders}
folders <- dir("./input")
folders <- subset(folders, folders %in% c("achtergrond","klauwkikker"))

i <- 1

for(f in folders){
  # get training data filelist
  filelist_trainingdata <- list.files("./input/trainingdata", full.names = TRUE)
  
  # get filelist
  filelist <- list.files(paste0("./input/", f), full.names = TRUE)
  filelist <- filelist[grepl(".wav", filelist, ignore.case = TRUE)]
  
  # get max number for new file
  # filter trainingdata filelist
  filelist_trainingdata <- filelist_trainingdata[grep(f, filelist_trainingdata)]
  maxnum <- max(as.numeric(gsub("[^0-9]", "", filelist_trainingdata)))
  
  gentestdata <- askYesNo(paste("Generate testdata for folder",f,"?"), default = "no")
  
  for(file in filelist){
    maxnum <- maxnum + 1
    i <- i + 1
    
    
    if(gentestdata){
      
      if(i == 3){
        fname <- gsub(pattern = paste0("./input/", f, "/"), replacement = "", x = file)
        # copy files to testdata folder
        file.copy(file, paste0("./input/testdata/", fname))
        file.remove(file)
        classification <- classification %>% 
          add_row(filename = fname, classification = f)
        # reset i
        i <- 1
      } else {
        # copy files to trainingdata folder
        file.copy(file, paste0("./input/trainingdata/", f, "_", maxnum, ".wav"))
        file.remove(file)
      }
    } else {
      # copy all files to trainingdata folder
      file.copy(file, paste0("./input/trainingdata/", f, "_", maxnum, ".wav"))
      file.remove(file)
    }
  }
}

write_csv2(classification, "./input/testdata/classification.txt")
```

```{r fun: WAVtowav}
source("./src/WAVtowav.R")
```

```{r set training data folder path}
TrainingWavFilesDir <- "./input/trainingdata/"

# Convert the .WAV files to .wav files
list.of.wav.files <- WAVtowav(TrainingWavFilesDir)
```

```{r}
test <- readWave(paste(TrainingWavFilesDir, "klauwkikker_1.wav", sep = ""))
```

```{r Read in clips and calculate MFCCs}
trainingdata <- gibbonR::MFCCFunction(input.dir=TrainingWavFilesDir, min.freq = min.freq, max.freq = max.freq,win.avg="standard")

# Convert to a factor
trainingdata$class <- as.factor(trainingdata$class)

# Output a table to see sample size
table(trainingdata$class)
```

```{r}
trainingdata <- trainingdata[, sapply(trainingdata, function(x) length(unique(x)) > 1)]
```

```{r}
trainingdata$class <- as.factor(trainingdata$class)


ml.model.svm <- e1071::svm(trainingdata[, 2:ncol(trainingdata)], trainingdata$class, kernel = "radial", 
                           cross = nrow(trainingdata),
                           probability = TRUE)

print(paste('SVM accuracy',ml.model.svm$tot.accuracy))
confusion_matrix <- 

ml.model.rf <- randomForest::randomForest(x=trainingdata[, 2:ncol(trainingdata)], y = trainingdata$class)


print(ml.model.rf)
confusion_matrix_rf <- as.data.frame(table(Actual = trainingdata$class, Predicted = ml.model.rf$predicted)) %>% 
  mutate(model_type = "RF") %>% 
  group_by(Actual) %>% 
  mutate(input_actual = sum(Freq)) %>%
  ungroup() %>%
  mutate(correct = case_when(Actual != Predicted ~ FALSE,
                             TRUE ~ TRUE),
         occ = (Freq/input_actual)*100)

confusion_matrix_svm <- as.data.frame(table(Actual = trainingdata$class, Predicted = ml.model.svm$fitted)) %>% 
  mutate(model_type = "SVM") %>% 
  group_by(Actual) %>% 
  mutate(input_actual = sum(Freq, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(correct = case_when(Actual != Predicted ~ FALSE,
                             TRUE ~ TRUE),
         occ = (Freq/input_actual)*100)

confusion_matrix <- rbind(confusion_matrix_rf, confusion_matrix_svm) %>% 
  pivot_wider(names_from = model_type, values_from = c(Freq, occ)) %>% 
  mutate(runDate = Sys.Date()) %>%
  write_csv(paste0("./output/confusion_matrix_", Sys.Date(),".csv"))

model_accuracy <- confusion_matrix %>% 
  filter(correct == TRUE) %>%
  filter(Actual != "onbekend") %>% 
  summarise(RF_accuracy = mean(occ_RF, na.rm = TRUE),
            SVM_accuracy = mean(occ_SVM, na.rm = TRUE)) %>% 
  mutate(runDate = Sys.Date()) %>% 
  write_csv(paste0("./output/model_accuracy_", Sys.Date(), ".csv"))
  
```

```{r}
source("./src/gibbonID_modified.R")

gibbonID(input.dir="./input/trainingdata",output.dir="./output/test/",win.avg='standard',add.spectrograms=FALSE,min.freq=min.freq,max.freq=max.freq,class='no.clustering')

gibbonID(input.dir="./input/trainingdata",output.dir="./output/test/",win.avg='standard',class='affinity.fixed', q.fixed=0.1,add.spectrograms=FALSE,min.freq=min.freq,max.freq=max.freq)
```

```{r save as rda}
saveRDS(trainingdata, "./output/trained_model.rda")
```

